/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页查询未删除的台账记录 */
        get: operations["listBatchRecords"];
        put?: never;
        /** 管理员创建台账记录；编号不能与历史已删除记录重复 */
        post: operations["createBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches/{batchId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: components["parameters"]["BatchId"];
            };
            cookie?: never;
        };
        /** 查询单条台账 */
        get: operations["getBatch"];
        /** 管理员修改台账；版本过期或关联活动周期时返回 409 */
        put: operations["updateBatch"];
        post?: never;
        /** 管理员逻辑删除台账，保留编号与追溯；料筐占用/使用中或批次仍关联料筐时拒绝 */
        delete: operations["deleteBatch"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/baskets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页查询未删除的台账记录 */
        get: operations["listBasketRecords"];
        put?: never;
        /** 管理员创建台账记录；编号不能与历史已删除记录重复 */
        post: operations["createBasket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/baskets/{basketNo}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                basketNo: components["parameters"]["BasketNo"];
            };
            cookie?: never;
        };
        /** 查询单条台账 */
        get: operations["getBasket"];
        /** 管理员修改台账；版本过期或关联活动周期时返回 409 */
        put: operations["updateBasket"];
        post?: never;
        /** 管理员逻辑删除台账，保留编号与追溯；料筐占用/使用中或批次仍关联料筐时拒绝 */
        delete: operations["deleteBasket"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/baskets/{basketNo}/qrcode": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                basketNo: components["parameters"]["BasketNo"];
            };
            cookie?: never;
        };
        /** 生成普通 QR Code PNG，码内容为完整料筐编号，不代表放行凭证 */
        get: operations["basketQRCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarm-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询所有未删除的自定义规则及其活动状态（最多 100 条）；普通用户只读 */
        get: operations["listAlarmRules"];
        put?: never;
        /** 创建自定义报警规则；条件最多嵌套 4 层、16 个叶子条件 */
        post: operations["createAlarmRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarm-rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ruleId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** 修改规则与通知策略；版本过期拒绝，所属炉子不可更改 */
        put: operations["updateAlarmRule"];
        post?: never;
        /** 逻辑删除规则并终止其活动报警和后续提醒；已进入发送流程的消息可能仍到达 */
        delete: operations["deleteAlarmRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/notifications/{alarmId}/cancel-reminders": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alarmId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 故障结束后取消待发送的重复提醒，并阻止迟到的提醒再次排队；幂等 */
        post: operations["cancelAlarmReminders"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 所有服务提供的进程存活检查 */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 所有服务提供的就绪检查 */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 自主注册普通用户并登录；请求不能指定角色 */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 撤销当前持久会话并清除 Cookie */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 修改本人用户名和显示名称，验证当前密码；用户 ID 和 Telegram 绑定不变
         * @description 用户名大小写不敏感；相同内容重复 PUT 幂等。不接受角色字段。
         */
        put: operations["updateMyProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 校验旧密码并修改密码，撤销本人全部会话，要求重新登录 */
        put: operations["changeMyPassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 管理员分页查看用户、角色和启用状态；不返回密码、会话或 Telegram 身份 */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{userId}/access": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * 修改其他账户角色与启用状态；不能停用或降级最后一个管理员
         * @description 不允许改变自己的角色/启用状态。相同内容重复 PUT 幂等。
         *     更改角色或启用状态后撤销目标用户全部会话；停用同时通过持久任务通知 notifier 暂停投递。
         *     其他权限修改事务占用锁时立即返回 409 ACCESS_UPDATE_BUSY；服务端处理上限为 5 秒，超时返回 503 ACCESS_UPDATE_TIMEOUT，客户端应查询当前状态核实结果。
         *     恢复启用保留原个人偏好，不补发停用期间通知。已经开始发送的消息可能仍到达。
         */
        put: operations["updateUserAccess"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/furnaces/{furnaceId}/camera-config": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                furnaceId: components["parameters"]["FurnaceId"];
            };
            cookie?: never;
        };
        /** 管理员查看已保存的完整 RTSP 地址与应用状态；响应不缓存，普通用户无权访问 */
        get: operations["getCameraConfig"];
        /**
         * 保存模拟摄像头或外部 RTSP 上游，后台应用到 MediaMTX
         * @description 有活动周期时拒绝修改。RTSP 地址加密持久化，在管理员设置页完整回显并允许编辑；仅接受 rtsp/rtsps。
         *     rtspUrl 省略表示保留已保存地址，首次选 rtsp 时必须提供。相同配置重复 PUT 幂等。
         *     应用过程禁止开启新周期；切换后留出解码重连时间。配置失败保留待应用状态，可重试或切回模拟源。
         */
        put: operations["configureCamera"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/account-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 按单调版本同步账号启停；忽略旧版本，停用时取消未发送通知 */
        put: operations["syncAccountAccess"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["currentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["myTelegram"];
        put?: never;
        post?: never;
        /** 解除本人绑定，同时取消尚未发送的该绑定通知 */
        delete: operations["unpairTelegram"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/telegram/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 提交 Bot 私聊 /start 返回的配对码；有效期 10 分钟，一次性消费
         * @description 一个网页账户只绑定一个 Telegram 私聊，一个 Telegram 账户不能同时绑定不同网页用户；先解绑才能换绑。
         */
        post: operations["pairTelegram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/notification-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 全量替换个人偏好；空炉子或类别集合表示不订阅，变更只影响尚未发送及未来通知 */
        put: operations["updateMyNotificationPreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/furnaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFurnaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/furnaces/{furnaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                furnaceId: components["parameters"]["FurnaceId"];
            };
            cookie?: never;
        };
        get: operations["getFurnace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/furnaces/{furnaceId}/manual-scans": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                furnaceId: components["parameters"]["FurnaceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 管理员对扫码失败的周期补录；始终执行 MES 校验，操作人取登录身份 */
        post: operations["manualScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/furnaces/{furnaceId}/resets": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                furnaceId: components["parameters"]["FurnaceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 管理员备用复位接口；正常界面由系统自动复位，无需点击
         * @description 请求立即入队；系统最多等待十五秒取得新鲜炉门状态并等待旧命令到期，随后自动关门、复位，以设备匹配反馈中止周期。不要求入口传感器为空或其他设备在线，不将未完成周期记为成功。
         */
        post: operations["resetFurnace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cycles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCycles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cycles/{cycleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: string;
            };
            cookie?: never;
        };
        get: operations["getCycle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAlarms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alarms/{alarmId}/acknowledgements": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alarmId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 管理员确认已查看，不清除故障，不放行设备 */
        post: operations["acknowledgeAlarm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SSE 快照流；连接后立即发送快照，之后状态更新；断线重连重新获取当前快照 */
        get: operations["eventStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/device-states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 接收适配器转发的状态；以 deviceId/bootId/seq 去重，离线状态允许重复 */
        post: operations["ingestDeviceStates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/scan-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ingestScanResult"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/barcode-detections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 持续扫码；稳定识别即视为入口到位，空闲时创建周期并进行 MES 校验
         * @description 不再要求入口 present 信号，不创建空画面超时周期。同一码停留只上报一次，移除至少三帧或换码后重新触发。活动周期内的新识别记录为忽略；过期十秒的结果不启动周期。幂等键使用 detectionId。
         */
        post: operations["ingestBarcodeDetection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/scada/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["scadaDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/scada/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 经 FUXA 发送一次；相同 commandId 可重发，由设备幂等执行
         * @description 命令持久化与重试归 core 所有；适配器没有隐藏的发送队列。
         */
        post: operations["writeDeviceCommand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/scan-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 以 sessionId 幂等创建；同时只允许一个未结束会话 */
        post: operations["createScanSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/camera": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cameraStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notificationJobs"];
        put?: never;
        post: operations["enqueueNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/users/{userId}/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get: operations["userTelegramState"];
        put?: never;
        post?: never;
        delete: operations["deleteTelegramBinding"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/users/{userId}/telegram/pair": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["consumePairCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/users/{userId}/notification-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        get?: never;
        put: operations["setUserNotificationPreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/mes/baskets/{basketNo}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                basketNo: string;
            };
            cookie?: never;
        };
        get: operations["basketEligibility"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/v1/sim/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["simulatedDeviceState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 仅模拟环境改变物理输入/故障；不直接修改业务状态 */
        patch: operations["injectDeviceScenario"];
        trace?: never;
    };
    "/internal/v1/sim/scene": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setCameraScene"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RuleCondition: components["schemas"]["RuleConditionLeaf"] | components["schemas"]["RuleConditionGroup"];
        RuleConditionLeaf: {
            /** @enum {string} */
            type: "condition";
            /** @enum {string} */
            field: "temperatureC" | "entryPresent" | "inFurnace" | "doorOpen" | "doorClosed" | "sensorOnline" | "doorOnline" | "lampOnline" | "temperatureOnline" | "cameraOnline" | "scanFailed" | "mesRejected" | "mesUnavailable" | "doorTimeout" | "entryTimeout" | "resetTimeout" | "workflowFault";
            /** @enum {string} */
            operator: "gt" | "gte" | "lt" | "lte" | "eq" | "ne";
            /** @description 温度字段使用数值；其他字段使用布尔值且只允许 eq/ne */
            value: number | boolean;
        };
        RuleConditionGroup: {
            /** @enum {string} */
            type: "group";
            /** @enum {string} */
            logic: "AND" | "OR";
            children: components["schemas"]["RuleCondition"][];
        };
        RuleChannels: {
            telegram: boolean;
            lamp: boolean;
        };
        AlarmRuleInput: {
            category?: components["schemas"]["NotificationCategory"];
            name: string;
            furnaceId: string;
            enabled: boolean;
            condition: components["schemas"]["RuleCondition"];
            /** @description 可选恢复条件；未设置时触发条件明确为假即恢复，无新数据不算恢复 */
            clearCondition?: components["schemas"]["RuleCondition"] | null;
            channels: components["schemas"]["RuleChannels"];
            /** @description 0 表示每次故障仅首次发送；否则按秒重复；重启不补发错过的全部提醒 */
            repeatSeconds: number & (0 | unknown);
            recoveries: boolean;
        };
        AlarmRuleUpdate: {
            category?: components["schemas"]["NotificationCategory"];
            name: string;
            furnaceId: string;
            enabled: boolean;
            condition: components["schemas"]["RuleCondition"];
            /** @description 可选恢复条件；未设置时触发条件明确为假即恢复，无新数据不算恢复 */
            clearCondition?: components["schemas"]["RuleCondition"] | null;
            channels: components["schemas"]["RuleChannels"];
            /** @description 0 表示每次故障仅首次发送；否则按秒重复；重启不补发错过的全部提醒 */
            repeatSeconds: number & (0 | unknown);
            recoveries: boolean;
            /** Format: int64 */
            version: number;
        };
        AlarmRule: {
            category?: components["schemas"]["NotificationCategory"];
            name: string;
            furnaceId: string;
            enabled: boolean;
            condition: components["schemas"]["RuleCondition"];
            /** @description 可选恢复条件；未设置时触发条件明确为假即恢复，无新数据不算恢复 */
            clearCondition?: components["schemas"]["RuleCondition"] | null;
            channels: components["schemas"]["RuleChannels"];
            /** @description 0 表示每次故障仅首次发送；否则按秒重复；重启不补发错过的全部提醒 */
            repeatSeconds: number & (0 | unknown);
            recoveries: boolean;
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            version: number;
            active: boolean;
            /** Format: date-time */
            nextReminderAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BatchInput: {
            batchNo: string;
            materialName: string;
            processSpec: string;
            /** @enum {string} */
            qualityStatus: "pending" | "passed" | "failed";
            enabled: boolean;
            notes: string;
        };
        BatchUpdate: {
            batchNo: string;
            materialName: string;
            processSpec: string;
            /** @enum {string} */
            qualityStatus: "pending" | "passed" | "failed";
            enabled: boolean;
            notes: string;
            /** Format: int64 */
            version: number;
        };
        Batch: {
            batchNo: string;
            materialName: string;
            processSpec: string;
            /** @enum {string} */
            qualityStatus: "pending" | "passed" | "failed";
            enabled: boolean;
            notes: string;
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description 关联未结束入炉周期 */
            inUse: boolean;
            /** Format: uuid */
            id: string;
        };
        BatchPage: {
            items: components["schemas"]["Batch"][];
            pagination: components["schemas"]["Pagination"];
        };
        BasketInput: {
            /** @description 必须完整匹配当前 BASKET_LENGTH / BASKET_PATTERN，默认 7 位字母数字；创建后不可更名 */
            basketNo: string;
            /** Format: uuid */
            batchId: string;
            quantity: number;
            enabled: boolean;
            notes: string;
        };
        BasketUpdate: {
            /** @description 必须完整匹配当前 BASKET_LENGTH / BASKET_PATTERN，默认 7 位字母数字；创建后不可更名 */
            basketNo: string;
            /** Format: uuid */
            batchId: string;
            quantity: number;
            enabled: boolean;
            notes: string;
            /** Format: int64 */
            version: number;
        };
        Basket: {
            /** @description 必须完整匹配当前 BASKET_LENGTH / BASKET_PATTERN，默认 7 位字母数字；创建后不可更名 */
            basketNo: string;
            /** Format: uuid */
            batchId: string;
            quantity: number;
            enabled: boolean;
            notes: string;
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description 关联未结束入炉周期 */
            inUse: boolean;
            batchNo: string;
            materialName: string;
            /** @enum {string} */
            qualityStatus: "pending" | "passed" | "failed";
            batchEnabled: boolean;
            occupied: boolean;
        };
        BasketPage: {
            items: components["schemas"]["Basket"][];
            pagination: components["schemas"]["Pagination"];
        };
        CatalogDelete: {
            /** Format: int64 */
            version: number;
        };
        AdmissionSnapshot: {
            basketNo: string;
            /** Format: int64 */
            basketVersion: number;
            basketEnabled: boolean;
            /** Format: uuid */
            batchId: string;
            batchNo: string;
            /** Format: int64 */
            batchVersion: number;
            batchEnabled: boolean;
            materialName: string;
            processSpec: string;
            quantity: number;
            /** @enum {string} */
            qualityStatus: "pending" | "passed" | "failed";
            /** Format: date-time */
            checkedAt: string;
        };
        ProfileUpdate: {
            username: string;
            displayName: string;
            /** Format: password */
            currentPassword: string;
        };
        PasswordChange: {
            /** Format: password */
            currentPassword: string;
            /**
             * Format: password
             * @description UTF-8 不超过 72 字节
             */
            newPassword: string;
        };
        UserAccessUpdate: {
            /** @enum {string} */
            role: "admin" | "user";
            enabled: boolean;
        };
        ManagedUser: components["schemas"]["User"] & {
            enabled: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        ManagedUserPage: {
            items: components["schemas"]["ManagedUser"][];
            pagination: components["schemas"]["Pagination"];
        };
        AccountAccess: {
            /** Format: uuid */
            userId: string;
            enabled: boolean;
            /** Format: int64 */
            version: number;
        };
        CameraConfigUpdate: {
            /** @enum {string} */
            mode: "simulated" | "rtsp";
            /** @description 完整 rtsp/rtsps 地址；可含摄像头凭据，仅管理员设置页回显 */
            rtspUrl?: string;
        };
        CameraConfig: {
            furnaceId: string;
            /** @enum {string} */
            mode: "simulated" | "rtsp";
            /** @description 当前来源的主机摘要 */
            sourceHost: string;
            /** @description 管理员可见的已保存完整 RTSP 地址；无保存地址时为空字符串，不写入日志 */
            readonly rtspUrl: string;
            hasSavedRtsp: boolean;
            /** Format: int64 */
            revision: number;
            applied: boolean;
            online: boolean;
            message: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            displayName: string;
            /** @enum {string} */
            role: "admin" | "user";
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        RegisterRequest: {
            username: string;
            /**
             * Format: password
             * @description 至少 8 字符，UTF-8 编码不超过 72 字节
             */
            password: string;
            displayName: string;
        };
        SessionResponse: {
            user: components["schemas"]["User"];
            /** Format: date-time */
            expiresAt: string;
        };
        PairRequest: {
            /** @description 8 位字母数字，允许输入分隔横线和小写 */
            code: string;
        };
        /** @enum {string} */
        NotificationCategory: "scan" | "mes" | "device" | "workflow" | "temperature" | "rules";
        NotificationPreferences: {
            /** @default true */
            enabled: boolean;
            furnaceIds: string[];
            categories: components["schemas"]["NotificationCategory"][];
            /** @default true */
            recoveries: boolean;
        };
        TelegramBinding: {
            displayName: string;
            /** Format: date-time */
            pairedAt: string;
        };
        TelegramState: {
            botUsername: string;
            botConfigured: boolean;
            botOnline: boolean;
            binding: components["schemas"]["TelegramBinding"] | null;
            preferences: components["schemas"]["NotificationPreferences"];
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            service: string;
        };
        APIError: {
            error: {
                code: string;
                message: string;
            };
        };
        Accepted: {
            id: string;
            /** @enum {string} */
            status: "accepted" | "ignored";
        };
        /** @enum {string} */
        CycleStatus: "SCANNING" | "VALIDATING" | "OPENING" | "WAITING_ENTRY" | "CLOSING" | "RESETTING" | "NEEDS_INPUT" | "BLOCKED" | "COMPLETED" | "ABORTED";
        Cycle: {
            mes?: components["schemas"]["MESResult"] | null;
            /** Format: uuid */
            id: string;
            furnaceId: string;
            basketNo: string;
            rawCode: string;
            status: components["schemas"]["CycleStatus"];
            reason: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            completedAt?: string | null;
        };
        CycleEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            cycleId: string;
            kind: string;
            message: string;
            /** Format: date-time */
            at: string;
        };
        CycleDetail: {
            cycle: components["schemas"]["Cycle"];
            events: components["schemas"]["CycleEvent"][];
            commands: components["schemas"]["CommandRecord"][];
        };
        /** @description MQTT state 原文；values 字段按 kind 使用 present/inFurnace、doorOpen/doorClosed、lampOn、temperatureC（摄氏度），以及 executionCount。 */
        DeviceState: {
            deviceId: string;
            furnaceId: string;
            /** @enum {string} */
            kind: "sensor" | "door" | "lamp" | "temperature";
            /** Format: uuid */
            bootId: string;
            /** Format: int64 */
            seq: number;
            /** Format: date-time */
            observedAt: string;
            values: {
                [key: string]: unknown;
            };
            commandId?: string;
            /** @enum {string} */
            executionStatus?: "IDLE" | "ACCEPTED" | "COMPLETED" | "REJECTED";
        };
        DeviceView: {
            deviceId: string;
            furnaceId: string;
            /** @enum {string} */
            kind: "sensor" | "door" | "lamp" | "temperature";
            online: boolean;
            reason: string;
            state: components["schemas"]["DeviceState"] | null;
        };
        /** @description SET_TEMPERATURE 由 FUXA 现场输入生成，只用于温度模拟器，必须提供有限的 temperatureC；保留启动编号、有效期和去重约束。 */
        DeviceCommand: {
            /** Format: uuid */
            commandId: string;
            cycleId: string;
            deviceId: string;
            furnaceId: string;
            /**
             * Format: double
             * @description SET_TEMPERATURE 必填，摄氏度
             */
            temperatureC?: number;
            /** Format: uuid */
            targetBootId: string;
            /** @enum {string} */
            action: "OPEN" | "CLOSE" | "RESET" | "ALARM_ON" | "ALARM_OFF" | "SET_TEMPERATURE";
            /** Format: date-time */
            issuedAt: string;
            /** Format: date-time */
            expiresAt: string;
        } & ({
            /** @enum {unknown} */
            action?: "SET_TEMPERATURE";
        } | {
            /** @enum {unknown} */
            action?: "OPEN" | "CLOSE" | "RESET" | "ALARM_ON" | "ALARM_OFF";
        });
        CommandRecord: {
            command: components["schemas"]["DeviceCommand"];
            /** @enum {string} */
            status: "PENDING" | "ACCEPTED" | "COMPLETED" | "EXPIRED" | "CANCELLED" | "UNKNOWN";
            attempts: number;
        };
        CameraState: {
            cameraId: string;
            online: boolean;
            sessionId: string;
            /** Format: date-time */
            lastFrameAt: string | null;
        };
        Furnace: {
            furnaceId: string;
            name: string;
            ready: boolean;
            /** @description IDLE 或 CycleStatus */
            phase: string;
            cycle: components["schemas"]["Cycle"] | null;
            devices: components["schemas"]["DeviceView"][];
            camera: components["schemas"]["CameraState"];
            previewUrl: string;
        };
        BarcodeDetection: {
            /** Format: uuid */
            detectionId: string;
            furnaceId: string;
            cameraId: string;
            rawCode: string;
            /** Format: date-time */
            observedAt: string;
        };
        ScanSession: {
            /** Format: uuid */
            sessionId: string;
            /** Format: uuid */
            cycleId: string;
            furnaceId: string;
            cameraId: string;
            /** Format: date-time */
            expiresAt: string;
        };
        ScanResult: {
            /** Format: uuid */
            sessionId: string;
            /** Format: uuid */
            cycleId: string;
            furnaceId: string;
            cameraId: string;
            /** @enum {string} */
            outcome: "DECODED" | "SCAN_TIMEOUT" | "CAMERA_OFFLINE" | "AMBIGUOUS";
            rawCode: string;
            /** Format: date-time */
            observedAt: string;
        };
        ManualScan: {
            /** Format: uuid */
            cycleId: string;
            rawCode: string;
            /**
             * @deprecated
             * @description 忽略此值，审计使用登录用户
             */
            operator?: string;
            reason: string;
        };
        OperatorAction: {
            /**
             * @deprecated
             * @description 忽略此值，审计使用登录用户
             */
            operator?: string;
            reason: string;
        };
        Alarm: {
            category?: components["schemas"]["NotificationCategory"];
            /** Format: uuid */
            ruleId?: string;
            /** Format: int64 */
            ruleVersion?: number;
            /**
             * @description 自定义报警结束原因，停用/删除规则不等于现场故障已消除
             * @enum {string}
             */
            resolution?: "condition_cleared" | "rule_disabled" | "rule_deleted" | "rule_migrated";
            /** @description 是否驱动现场声光，缺省为系统报警的 true */
            lamp?: boolean;
            /** Format: uuid */
            id: string;
            furnaceId: string;
            cycleId: string;
            code: string;
            message: string;
            /** Format: date-time */
            raisedAt: string;
            /** Format: date-time */
            acknowledgedAt: string | null;
            /** Format: date-time */
            recoveredAt: string | null;
            operator: string;
        };
        NotificationRequest: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            alarmId: string;
            furnaceId: string;
            /** @enum {string} */
            kind: "ALARM" | "RECOVERY" | "REMINDER";
            category?: components["schemas"]["NotificationCategory"];
            text: string;
            /** Format: date-time */
            createdAt: string;
        };
        Notification: components["schemas"]["NotificationRequest"] & {
            /** @enum {string} */
            status: "pending" | "sent" | "failed" | "unknown" | "cancelled";
            attempts: number;
            lastError: string;
            /** Format: date-time */
            sentAt: string | null;
            /** Format: date-time */
            nextAttemptAt: string;
        };
        /** @description 从 PostgreSQL 台账校验；0 不存在，1 允许，2 禁用或质检未通过。未知编号不得放行。 */
        MESResult: {
            reason: string;
            snapshot?: components["schemas"]["AdmissionSnapshot"] | null;
            basketNo: string;
            /** @enum {integer} */
            result: 0 | 1 | 2;
            message: string;
        };
        Pagination: {
            page: number;
            pageSize: number;
            total: number;
        };
        CyclePage: {
            items: components["schemas"]["Cycle"][];
            pagination: components["schemas"]["Pagination"];
        };
        AlarmPage: {
            items: components["schemas"]["Alarm"][];
            pagination: components["schemas"]["Pagination"];
        };
        NotificationPage: {
            items: components["schemas"]["Notification"][];
            pagination: components["schemas"]["Pagination"];
        };
        StreamSnapshot: {
            /**
             * Format: int64
             * @description 自定义报警规则与活动状态版本，变化后刷新规则和报警列表
             */
            rulesVersion: number;
            /**
             * Format: int64
             * @description 持久台账版本；变化或重连后重新查询列表，不覆盖编辑草稿
             */
            catalogVersion: number;
            /** Format: date-time */
            at: string;
            furnaces: components["schemas"]["Furnace"][];
            activeAlarmCount: number;
        };
        SimulationInput: {
            present?: boolean;
            inFurnace?: boolean;
            jammed?: boolean;
            /** @description 暂停状态发布以测试过期 */
            muted?: boolean;
            /** @description 仅模拟人工消除卡门故障 */
            forceClosed?: boolean;
        };
        CameraScene: {
            codes: string[];
            /** @default false */
            paused: boolean;
        };
    };
    responses: {
        /** @description 会话有效 12 小时，凭据仅通过 HttpOnly SameSite=Strict Cookie 返回 */
        Session: {
            headers: {
                "Set-Cookie"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SessionResponse"];
            };
        };
        /** @description 结构化错误；message 不包含凭据或内部堆栈 */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description 请求已接收；重复请求返回同一对象，不代表设备执行完成 */
        Accepted: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Accepted"];
            };
        };
    };
    parameters: {
        BatchId: string;
        BasketNo: string;
        UserId: string;
        FurnaceId: string;
        IdempotencyKey: string;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listBatchRecords: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchPage"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    createBatch: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchInput"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batchId: components["parameters"]["BatchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    updateBatch: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                batchId: components["parameters"]["BatchId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchUpdate"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    deleteBatch: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                batchId: components["parameters"]["BatchId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogDelete"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listBasketRecords: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                q?: string;
                batchId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BasketPage"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    createBasket: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BasketInput"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getBasket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                basketNo: components["parameters"]["BasketNo"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查询结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Basket"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    updateBasket: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                basketNo: components["parameters"]["BasketNo"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BasketUpdate"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    deleteBasket: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                basketNo: components["parameters"]["BasketNo"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogDelete"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    basketQRCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                basketNo: components["parameters"]["BasketNo"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 二维码标签 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listAlarmRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 规则列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlarmRule"][];
                };
            };
            401: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    createAlarmRule: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlarmRuleInput"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    updateAlarmRule: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlarmRuleUpdate"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    deleteAlarmRule: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CatalogDelete"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    cancelAlarmReminders: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alarmId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已结束此报警的重复提醒 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 进程存活（不代表依赖可用） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 能处理本服务请求 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: components["responses"]["Error"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: components["responses"]["Session"];
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: components["responses"]["Session"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已退出 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description 更新后的本人资料 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    changeMyPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description 密码已修改，所有会话已撤销，Cookie 已清除 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedUserPage"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    updateUserAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserAccessUpdate"];
            };
        };
        responses: {
            /** @description 更新后的用户 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedUser"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getCameraConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                furnaceId: components["parameters"]["FurnaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 摄像头配置状态；已应用不等于视频已连通 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraConfig"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    configureCamera: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                furnaceId: components["parameters"]["FurnaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraConfigUpdate"];
            };
        };
        responses: {
            /** @description 配置已保存，查询 applied 和 online 区分应用与连通结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraConfig"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    syncAccountAccess: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountAccess"];
            };
        };
        responses: {
            /** @description 已应用或已处理该版本 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    currentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前登录用户，不含密码或会话密钥 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    myTelegram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 本人绑定状态、Bot 链接信息及通知偏好，不暴露 Chat ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramState"];
                };
            };
            401: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    unpairTelegram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已解绑；重复调用无副作用 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    pairTelegram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairRequest"];
            };
        };
        responses: {
            /** @description 配对完成 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramState"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    updateMyNotificationPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationPreferences"];
            };
        };
        responses: {
            /** @description 已保存 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreferences"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    listFurnaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 全部已配置炉子及实时状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Furnace"][];
                };
            };
            503: components["responses"]["Error"];
        };
    };
    getFurnace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                furnaceId: components["parameters"]["FurnaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 单台炉子的可恢复快照 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Furnace"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    manualScan: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                furnaceId: components["parameters"]["FurnaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualScan"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    resetFurnace: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                furnaceId: components["parameters"]["FurnaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperatorAction"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listCycles: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                furnaceId?: string;
                basketNo?: string;
                status?: components["schemas"]["CycleStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 按创建时间倒序分页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CyclePage"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getCycle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 周期及按发生顺序排列的事件与命令 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleDetail"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listAlarms: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                furnaceId?: string;
                active?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 活动及历史报警；确认和恢复为不同字段 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlarmPage"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    acknowledgeAlarm: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                alarmId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperatorAction"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 仅当前用户的通知投递状态；unknown 表示外部发送结果不确定 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPage"];
                };
            };
            503: components["responses"]["Error"];
        };
    };
    eventStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description event=state，data 为 StreamSnapshot JSON；不是可重放审计日志 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    ingestDeviceStates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceView"][];
            };
        };
        responses: {
            /** @description 状态已接收；不是业务完成确认 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    ingestScanResult: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanResult"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    ingestBarcodeDetection: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BarcodeDetection"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    scadaDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 适配器状态快照；FUXA 缓存不代表设备在线 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceView"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    writeDeviceCommand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceCommand"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    createScanSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanSession"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    cameraStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 拉流状态，不包含摄像头凭据或原始 RTSP URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraState"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    notificationJobs: {
        parameters: {
            query: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 持久通知队列 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPage"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    enqueueNotification: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationRequest"];
            };
        };
        responses: {
            202: components["responses"]["Accepted"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    userTelegramState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 由 core 使用会话中的 userId 调用 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramState"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    deleteTelegramBinding: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 绑定及未发送投递已撤销 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    consumePairCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairRequest"];
            };
        };
        responses: {
            /** @description 原子消费配对码并绑定用户 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramState"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    setUserNotificationPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationPreferences"];
            };
        };
        responses: {
            /** @description 本人偏好已保存 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPreferences"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    basketEligibility: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                basketNo: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description result 1=允许，0=不存在，2=质量异常；通信错误使用非 2xx */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MESResult"];
                };
            };
            401: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    simulatedDeviceState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 仅测试检查设备行为，core 不使用此接口读取设备状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceState"];
                };
            };
        };
    };
    injectDeviceScenario: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationInput"];
            };
        };
        responses: {
            /** @description 输入已更新 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    setCameraScene: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraScene"];
            };
        };
        responses: {
            /** @description 后续视频帧使用新场景 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
}
