<script setup lang="ts">
import {computed,onMounted,ref,watch} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {call,get,formatTime,type AlarmRule,type AlarmRuleInput,type RuleCondition,type Furnace} from '../api/client'
import {currentUser} from '../auth'
import {rulesVersion} from '../liveVersions'
import RuleConditionEditor from './RuleConditionEditor.vue'
const rules=ref<AlarmRule[]>([]),furnaces=ref<Furnace[]>([]),error=ref(''),filter=ref(''),dialog=ref(false),editing=ref<AlarmRule|null>(null),busy=ref(false),formError=ref(''),clearEnabled=ref(false)
const form=ref<AlarmRuleInput>(fresh())
const categories=[['rules','自定义规则'],['temperature','炉温'],['device','设备连接'],['scan','扫码'],['mes','MES 校验'],['workflow','入炉流程']]
const labels:Record<string,string>={temperatureC:'炉温',entryPresent:'入口到位',inFurnace:'炉内到位',doorOpen:'门已开',doorClosed:'门已关',sensorOnline:'到位传感器在线',doorOnline:'炉门在线',lampOnline:'报警器在线',temperatureOnline:'炉温传感器在线',cameraOnline:'摄像头在线',scanFailed:'扫码失败',mesRejected:'MES 拒绝',mesUnavailable:'MES 通信失败',doorTimeout:'开关门超时',entryTimeout:'入炉超时',resetTimeout:'复位超时',workflowFault:'执行异常待处理'}
let key='',request=0
const admin=computed(()=>currentUser.value?.role==='admin')
const visible=computed(()=>rules.value.filter(r=>!filter.value||r.furnaceId===filter.value))
function fresh():AlarmRuleInput{return {name:'',furnaceId:'',category:'rules',enabled:true,condition:{type:'condition',field:'temperatureC',operator:'gt',value:800},channels:{telegram:true,lamp:true},repeatSeconds:0,recoveries:true}}
function cloneCondition(c:RuleCondition):RuleCondition{return JSON.parse(JSON.stringify(c))}
function input(r:AlarmRule):AlarmRuleInput{return {name:r.name,furnaceId:r.furnaceId,category:r.category??'rules',enabled:r.enabled,condition:cloneCondition(r.condition),clearCondition:r.clearCondition?cloneCondition(r.clearCondition):undefined,channels:{...r.channels},repeatSeconds:r.repeatSeconds,recoveries:r.recoveries}}
function describe(c:RuleCondition):string{if(c.type==='group')return '('+c.children.map(describe).join(' '+c.logic+' ')+')';return (labels[c.field]??c.field)+' '+({gt:'>',gte:'≥',lt:'<',lte:'≤',eq:'=',ne:'≠'}[c.operator])+' '+(typeof c.value==='boolean'?(c.value?'是':'否'):c.value)}
async function load(){const n=++request;try{const [r,f]=await Promise.all([get<AlarmRule[]>('/alarm-rules'),get<Furnace[]>('/furnaces')]);if(n!==request)return;rules.value=r;furnaces.value=f;error.value=''}catch(e){if(n===request)error.value=(e as Error).message}}
function open(r?:AlarmRule){editing.value=r??null;form.value=r?input(r):fresh();if(!r)form.value.furnaceId=furnaces.value[0]?.furnaceId??'';clearEnabled.value=!!r?.clearCondition;if(!form.value.clearCondition)form.value.clearCondition={type:'condition',field:'temperatureC',operator:'lte',value:795};key=crypto.randomUUID();formError.value='';dialog.value=true}
function boundsExample(){form.value.condition={type:'group',logic:'OR',children:[{type:'condition',field:'temperatureC',operator:'lt',value:650},{type:'condition',field:'temperatureC',operator:'gt',value:850}]};form.value.clearCondition={type:'group',logic:'AND',children:[{type:'condition',field:'temperatureC',operator:'gte',value:655},{type:'condition',field:'temperatureC',operator:'lte',value:845}]};clearEnabled.value=true}
async function save(){formError.value='';if(!Number.isInteger(form.value.repeatSeconds)){formError.value='请填写有效的提醒间隔';return}busy.value=true;try{const body={...form.value,clearCondition:clearEnabled.value?form.value.clearCondition:null,...(editing.value?{version:editing.value.version}:{})};await call(editing.value?'PUT':'POST','/alarm-rules'+(editing.value?'/'+editing.value.id:''),body,key);dialog.value=false;await load();ElMessage.success('报警规则已保存，将按当前状态评估')}catch(e){formError.value=(e as Error).message}finally{busy.value=false}}
async function toggle(r:AlarmRule){try{await call('PUT','/alarm-rules/'+r.id,{...input(r),enabled:!r.enabled,version:r.version},crypto.randomUUID());await load()}catch(e){ElMessage.error((e as Error).message)}}
async function remove(r:AlarmRule){try{await ElMessageBox.confirm('删除会结束这条规则的活动报警，停止后续提醒；历史记录保留。','删除报警规则',{confirmButtonText:'删除',cancelButtonText:'取消',type:'warning'});await call('DELETE','/alarm-rules/'+r.id,{version:r.version},crypto.randomUUID());await load()}catch(e){if(e instanceof Error)ElMessage.error(e.message)}}
watch(rulesVersion,()=>void load());onMounted(load)
</script>
<template>
 <div class="section-title"><div><div class="eyebrow">ALARM RULES</div><h1>报警规则</h1><p>统一管理温度、设备状态与流程故障的触发条件和通知节奏。</p></div><el-button v-if="admin" type="primary" @click="open()">新增规则</el-button></div>
 <section class="panel table-panel"><div class="filter-row"><el-select v-model="filter" clearable placeholder="全部炉子" aria-label="按炉子筛选报警规则" style="width:200px"><el-option v-for="f in furnaces" :key="f.furnaceId" :value="f.furnaceId" :label="f.name"/></el-select><el-button @click="load">刷新</el-button><span class="muted small">自动同步 · {{visible.length}} 条规则</span></div><el-alert v-if="error" :title="error" type="error" :closable="false"/>
 <el-table :data="visible" empty-text="暂无规则；管理员可新增条件与报警方式。"><el-table-column label="规则" min-width="180"><template #default="{row}"><strong>{{row.name}}</strong><p class="small muted">{{row.furnaceId}} · v{{row.version}}</p></template></el-table-column><el-table-column label="触发条件" min-width="210"><template #default="{row}"><span class="condition-description">{{describe(row.condition)}}</span></template></el-table-column><el-table-column label="状态" width="105"><template #default="{row}"><span :class="['pill',!row.enabled?'neutral':row.active?'warn':'good']">{{!row.enabled?'停用':row.active?'报警中':'监测中'}}</span></template></el-table-column><el-table-column label="报警方式" min-width="160"><template #default="{row}"><div class="small">网页{{row.channels.lamp?' · 声光':''}}</div><div class="small">{{row.channels.telegram?(row.repeatSeconds?'TG 每 '+row.repeatSeconds+' 秒':'TG 首次一次'):'不发送 TG'}}</div><div v-if="row.channels.telegram" class="small muted">{{row.recoveries?'发送恢复通知':'不发送恢复通知'}}</div></template></el-table-column><el-table-column v-if="admin" label="操作" width="185"><template #default="{row}"><el-button link type="primary" @click="open(row)">编辑</el-button><el-button link @click="toggle(row)">{{row.enabled?'停用':'启用'}}</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table></section>
 <div class="rules-help"><p>预置规则与新建规则使用同一套引擎，均可编辑、停用或删除。关闭报警不解除 MES 拒绝、掉线暂停等业务约束。</p><p>确认“已查看”不会停止定时提醒；恢复条件满足、停用或删除规则后停止。缺少新数据的条件视为未知，不会冒充故障恢复。</p><p>Telegram 还需符合接收者的个人订阅；规则的“通知分组”与个人通知中的类别对应。已经开始发送的消息可能仍到达。</p></div>
 <el-dialog v-model="dialog" :title="editing?'编辑报警规则':'新增报警规则'" width="min(880px,96vw)" :close-on-click-modal="false"><el-alert v-if="formError" :title="formError" type="error" :closable="false"/>
 <el-form label-position="top"><div class="rule-grid"><el-form-item label="规则名称"><el-input v-model="form.name" aria-label="规则名称" maxlength="80"/></el-form-item><el-form-item label="所属炉子"><el-select v-model="form.furnaceId" :disabled="!!editing" aria-label="规则所属炉子"><el-option v-for="f in furnaces" :key="f.furnaceId" :label="f.name" :value="f.furnaceId"/></el-select></el-form-item></div>
 <div class="editor-title"><h3>触发条件</h3><el-button size="small" @click="boundsExample">填入温度上下限示例</el-button></div><RuleConditionEditor v-model="form.condition"/>
 <div class="clear-option"><el-checkbox v-model="clearEnabled">自定义恢复条件（可设置回差）</el-checkbox><p class="muted small">未开启时，触发条件明确不成立即恢复；触发与恢复同时成立时保持报警，避免反复跳变。AND / OR 可嵌套，最多 4 层、16 个叶子条件。</p></div><RuleConditionEditor v-if="clearEnabled&&form.clearCondition" v-model="form.clearCondition"/>
 <div class="rule-grid rule-options"><el-form-item label="报警方式"><div><p class="small">网页报警记录始终保留</p><el-checkbox v-model="form.channels.lamp">现场声光（模拟器）</el-checkbox><el-checkbox v-model="form.channels.telegram">Telegram</el-checkbox></div></el-form-item><el-form-item label="通知分组"><el-select v-model="form.category" aria-label="通知分组"><el-option v-for="[v,label] in categories" :key="v" :value="v" :label="label"/></el-select></el-form-item></div>
 <div v-if="form.channels.telegram" class="telegram-options"><el-radio-group :model-value="form.repeatSeconds===0?'once':'repeat'" @update:model-value="form.repeatSeconds=$event==='once'?0:60"><el-radio value="once">每次故障首次发送一次</el-radio><el-radio value="repeat">故障持续时定时提醒</el-radio></el-radio-group><div v-if="form.repeatSeconds>0" class="repeat-input"><span>提醒间隔（秒）</span><el-input-number v-model="form.repeatSeconds" :min="10" :max="86400" :precision="0" :step="10" aria-label="提醒间隔秒数"/></div><el-checkbox v-model="form.recoveries">结束报警时另发一次恢复 / 规则结束通知</el-checkbox></div>
 <el-form-item label="启用规则" style="margin-top:18px"><el-switch v-model="form.enabled" aria-label="启用规则"/></el-form-item><p class="muted small">启用后立即按当前状态评估，可能触发报警。修改只影响后续判断和提醒，历史消息不会被撤回。</p></el-form>
 <template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="busy" @click="save">保存规则</el-button></template></el-dialog>
</template>
<style scoped>
.rule-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.editor-title{display:flex;align-items:center;justify-content:space-between;margin:10px 0}.editor-title h3{font-size:14px}.clear-option{margin:16px 0 10px}.rule-options{margin-top:24px}.telegram-options{padding:16px;background:#f2f7f5;border-radius:6px}.repeat-input{display:flex;align-items:center;gap:12px;margin:12px 0;font-size:12px}.rules-help{margin-top:20px;color:var(--muted);font-size:12px;line-height:1.8}.rules-help p{margin:6px 0}.condition-description{font-size:12px;line-height:1.6;word-break:break-word}@media(max-width:650px){.rule-grid{grid-template-columns:1fr;gap:0}}
</style>
