<script setup lang="ts">
import {computed,onMounted,ref,watch} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {call,get,type Batch,type Basket,type BatchPage,type BasketPage,type BatchInput,type BasketInput} from '../api/client'
import {currentUser} from '../auth'
import {catalogVersion} from '../liveVersions'
const mode=ref<'baskets'|'batches'>('baskets'),query=ref(''),page=ref(1),total=ref(0),loading=ref(false),error=ref('')
const batches=ref<Batch[]>([]),baskets=ref<Basket[]>([]),options=ref<Batch[]>([]),busy=ref(false),dialog=ref(false),formError=ref(''),qr=ref('')
const admin=computed(()=>currentUser.value?.role==='admin')
const editing=ref<{kind:'baskets'|'batches',id:string,version:number}|null>(null)
const kind=ref<'baskets'|'batches'>('baskets')
const batchForm=ref<BatchInput>({batchNo:'',materialName:'',processSpec:'',qualityStatus:'pending',enabled:true,notes:''})
const basketForm=ref<BasketInput>({basketNo:'',batchId:'',quantity:1,enabled:true,notes:''})
const quality:Record<string,string>={pending:'待检',passed:'合格',failed:'不合格'}
let key='',requestNumber=0
async function load(){const n=++requestNumber;loading.value=true;try{const result=await get<BatchPage|BasketPage>(`/${mode.value}?page=${page.value}&pageSize=12&q=${encodeURIComponent(query.value)}`);if(n!==requestNumber)return;total.value=result.pagination.total;if(mode.value==='batches')batches.value=(result as BatchPage).items;else baskets.value=(result as BasketPage).items;error.value=''}catch(e){if(n===requestNumber)error.value=(e as Error).message}finally{if(n===requestNumber)loading.value=false}}
async function searchBatches(q=''){try{const result=await get<BatchPage>('/batches?pageSize=100&q='+encodeURIComponent(q));options.value=result.items}catch(e){formError.value=(e as Error).message}}
async function open(row?:Batch|Basket){kind.value=mode.value;formError.value='';key=crypto.randomUUID();editing.value=row?{kind:kind.value,id:kind.value==='batches'?(row as Batch).id:(row as Basket).basketNo,version:row.version}:null
 if(kind.value==='batches'){const b=row as Batch|undefined;batchForm.value={batchNo:b?.batchNo??'',materialName:b?.materialName??'',processSpec:b?.processSpec??'',qualityStatus:b?.qualityStatus??'pending',enabled:b?.enabled??true,notes:b?.notes??''}}
 else{const b=row as Basket|undefined;basketForm.value={basketNo:b?.basketNo??'',batchId:b?.batchId??'',quantity:b?.quantity??1,enabled:b?.enabled??true,notes:b?.notes??''};await searchBatches();if(b&&!options.value.some(o=>o.id===b.batchId)){try{options.value.push(await get<Batch>('/batches/'+encodeURIComponent(b.batchId)))}catch(e){formError.value=(e as Error).message}}}
 dialog.value=true
}
async function save(){busy.value=true;formError.value='';try{const edit=editing.value;const body=kind.value==='batches'?batchForm.value:basketForm.value;await call(''+(edit?'PUT':'POST'),`/${kind.value}${edit?'/'+encodeURIComponent(edit.id):''}`,{...body,...(edit?{version:edit.version}:{})},key);dialog.value=false;await load();ElMessage.success('台账已保存，其他页面会自动同步')}catch(e){formError.value=(e as Error).message}finally{busy.value=false}}
async function remove(row:Batch|Basket){const id=mode.value==='batches'?(row as Batch).id:(row as Basket).basketNo;try{await ElMessageBox.confirm('删除后记录不再参与 MES 校验，历史追溯和编号仍保留，编号不能重复使用。','删除台账记录',{type:'warning',confirmButtonText:'删除',cancelButtonText:'取消'});await call('DELETE',`/${mode.value}/${encodeURIComponent(id)}`,{version:row.version},crypto.randomUUID());await load();ElMessage.success('记录已删除')}catch(e){if(e instanceof Error)ElMessage.error(e.message)}}
function status(b:Basket){if(b.occupied)return '已占用';if(b.inUse)return '入炉处理中';if(!b.enabled||!b.batchEnabled)return '已停用';if(b.qualityStatus!=='passed')return '禁止入炉 · '+quality[b.qualityStatus];return '台账可放行'}
watch(mode,()=>{page.value=1;query.value='';void load()});watch(catalogVersion,()=>void load());onMounted(load)
</script>
<template>
 <div class="section-title"><div><div class="eyebrow">MES / PRODUCTION CATALOG</div><h1>料筐与批次</h1><p>扫码按真实台账校验；列表实时同步，编辑草稿不会被其他人的修改覆盖。</p></div><el-button v-if="admin" type="primary" @click="open()">{{mode==='baskets'?'新增料筐':'新增批次'}}</el-button></div>
 <div class="catalog-toolbar"><el-radio-group v-model="mode"><el-radio-button value="baskets">料筐台账</el-radio-button><el-radio-button value="batches">生产批次</el-radio-button></el-radio-group><span class="small muted">{{admin?'管理员可维护台账':'普通用户 · 只读'}} · 自动同步</span></div>
 <section class="panel table-panel"><form class="filter-row" @submit.prevent="page=1;load()"><el-input v-model="query" :placeholder="mode==='baskets'?'料筐号、批次号或物料':'批次号或物料'" aria-label="搜索台账" clearable style="max-width:320px"/><el-button native-type="submit">查询</el-button><el-button @click="load">刷新</el-button></form><el-alert v-if="error" :title="error" type="error" :closable="false"/>
 <el-table v-if="mode==='baskets'" :data="baskets" v-loading="loading" empty-text="暂无料筐。管理员先创建批次，再登记料筐。"><el-table-column prop="basketNo" label="料筐编号" min-width="115"/><el-table-column prop="batchNo" label="批次" min-width="135"/><el-table-column prop="materialName" label="物料" min-width="120"/><el-table-column prop="quantity" label="数量" width="75"/><el-table-column label="入炉资格" min-width="150"><template #default="{row}"><span :class="['pill',status(row)==='台账可放行'?'good':'warn']">{{status(row)}}</span></template></el-table-column><el-table-column label="操作" :width="admin?210:90"><template #default="{row}"><el-button link type="primary" @click="qr=row.basketNo">二维码</el-button><el-button v-if="admin" link :disabled="row.inUse||row.occupied" @click="open(row)">编辑</el-button><el-button v-if="admin" link type="danger" :disabled="row.inUse||row.occupied" @click="remove(row)">删除</el-button></template></el-table-column></el-table>
 <el-table v-else :data="batches" v-loading="loading" empty-text="暂无批次。新增批次后维护物料与质检状态。"><el-table-column prop="batchNo" label="批次编号" min-width="150"/><el-table-column prop="materialName" label="物料" min-width="130"/><el-table-column prop="processSpec" label="工艺说明" min-width="155" show-overflow-tooltip/><el-table-column label="质检" width="100"><template #default="{row}"><span :class="['pill',row.qualityStatus==='passed'?'good':'warn']">{{quality[row.qualityStatus]}}</span></template></el-table-column><el-table-column label="状态" width="95"><template #default="{row}">{{row.enabled?'启用':'停用'}}</template></el-table-column><el-table-column v-if="admin" label="操作" width="145"><template #default="{row}"><el-button link :disabled="row.inUse" @click="open(row)">编辑</el-button><el-button link type="danger" :disabled="row.inUse" @click="remove(row)">删除</el-button></template></el-table-column></el-table>
 <div class="pagination"><span class="muted">共 {{total}} 条记录</span><el-pagination v-model:current-page="page" :page-size="12" :total="total" layout="prev,pager,next" @current-change="load"/></div></section>
 <p class="catalog-help muted">料筐存在、已启用，且关联批次启用并质检合格后，MES 才能放行。已占用料筐不能重复入炉；本期没有出炉释放占用功能。</p>
 <el-dialog v-model="dialog" :title="(editing?'编辑':'新增')+(kind==='batches'?'批次':'料筐')" width="min(580px,94vw)" :close-on-click-modal="false"><el-alert v-if="formError" :title="formError" type="error" :closable="false"/>
 <el-form label-position="top" @submit.prevent="save"><template v-if="kind==='batches'"><el-form-item label="批次编号"><el-input v-model="batchForm.batchNo" aria-label="批次编号" maxlength="40" placeholder="例如 LOT-20260922-01"/></el-form-item><el-form-item label="物料名称"><el-input v-model="batchForm.materialName" aria-label="物料名称" maxlength="100"/></el-form-item><el-form-item label="工艺说明"><el-input v-model="batchForm.processSpec" aria-label="工艺说明" maxlength="200"/></el-form-item><el-form-item label="质检状态"><el-select v-model="batchForm.qualityStatus" aria-label="质检状态"><el-option value="pending" label="待检 · 禁止入炉"/><el-option value="passed" label="合格 · 可校验放行"/><el-option value="failed" label="不合格 · 禁止入炉"/></el-select></el-form-item><el-form-item label="启用批次"><el-switch v-model="batchForm.enabled" aria-label="启用批次"/></el-form-item><el-form-item label="备注"><el-input v-model="batchForm.notes" type="textarea" aria-label="批次备注" maxlength="500"/></el-form-item></template>
 <template v-else><el-form-item label="料筐编号（默认 7 位字母数字，创建后不可更名）"><el-input v-model="basketForm.basketNo" :disabled="!!editing" aria-label="料筐编号" maxlength="64" placeholder="例如 B000001"/></el-form-item><el-form-item label="关联批次"><el-select v-model="basketForm.batchId" filterable remote :remote-method="searchBatches" aria-label="关联批次" placeholder="输入批次号或物料搜索" style="width:100%"><el-option v-for="b in options" :key="b.id" :value="b.id" :label="b.batchNo+' · '+b.materialName+' · '+quality[b.qualityStatus]"/></el-select></el-form-item><el-form-item label="装载数量"><el-input-number v-model="basketForm.quantity" :min="1" :max="100000" :precision="0" aria-label="装载数量"/></el-form-item><el-form-item label="启用料筐入炉"><el-switch v-model="basketForm.enabled" aria-label="启用料筐入炉"/></el-form-item><el-form-item label="备注"><el-input v-model="basketForm.notes" type="textarea" aria-label="料筐备注" maxlength="500"/></el-form-item></template></el-form>
 <template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="busy" @click="save">保存</el-button></template></el-dialog>
 <el-dialog :model-value="!!qr" title="料筐 QR 标签" width="min(440px,94vw)" @close="qr=''"><div v-if="qr" class="qr-label"><img :src="'/api/v1/baskets/'+encodeURIComponent(qr)+'/qrcode'" :alt="'料筐 '+qr+' 的二维码'" width="280" height="280"/><h2 class="mono">{{qr}}</h2><p class="muted small">二维码标识料筐，是否放行由台账与占用状态决定。</p><a :href="'/api/v1/baskets/'+encodeURIComponent(qr)+'/qrcode'" :download="qr+'.png'" class="text-link">下载 PNG 标签</a></div></el-dialog>
</template>
<style scoped>
.catalog-toolbar{display:flex;justify-content:space-between;gap:16px;margin-bottom:20px;align-items:center}.catalog-help{font-size:12px;line-height:1.8;margin-top:18px}.qr-label{text-align:center}.qr-label img{max-width:100%;height:auto}.qr-label h2{margin:5px 0 12px}.qr-label p{margin-bottom:16px}@media(max-width:600px){.catalog-toolbar{align-items:flex-start;flex-direction:column}}
</style>
