<script setup lang="ts">
import {onMounted,onBeforeUnmount,ref,watch} from 'vue'
import {ElMessage} from 'element-plus'
import {call,get,type User,type Furnace,type CameraConfig} from '../api/client'
import {currentUser} from '../auth'
const username=ref(currentUser.value?.username??''),displayName=ref(currentUser.value?.displayName??'')
const profilePassword=ref(''),oldPassword=ref(''),newPassword=ref(''),confirmPassword=ref(''),busy=ref('')
const furnaces=ref<Furnace[]>([]),selected=ref(''),camera=ref<CameraConfig>(),mode=ref<'simulated'|'rtsp'>('simulated'),rtsp=ref(''),cameraError=ref('')
const cameraDirty=ref(false)
let timer:ReturnType<typeof setInterval>|undefined
async function profile(){busy.value='profile';try{currentUser.value=await call<User>('PUT','/me/profile',{username:username.value,displayName:displayName.value,currentPassword:profilePassword.value});profilePassword.value='';username.value=currentUser.value.username;ElMessage.success('账户资料已更新')}catch(e){ElMessage.error((e as Error).message)}finally{busy.value=''}}
async function password(){if(newPassword.value!==confirmPassword.value){ElMessage.warning('两次新密码不一致');return}busy.value='password';try{await call('PUT','/me/password',{currentPassword:oldPassword.value,newPassword:newPassword.value});oldPassword.value='';newPassword.value='';confirmPassword.value='';currentUser.value=null;ElMessage.success('密码已修改，请使用新密码重新登录')}catch(e){ElMessage.error((e as Error).message)}finally{busy.value=''}}
async function refreshCamera(reset=false){if(!selected.value)return;const id=selected.value;try{const c=await get<CameraConfig>(`/furnaces/${id}/camera-config`);if(id!==selected.value||camera.value&&c.revision<camera.value.revision)return;camera.value=c;cameraError.value='';if(reset||!cameraDirty.value){mode.value=c.mode;rtsp.value=c.rtspUrl;cameraDirty.value=false}}catch(e){cameraError.value=(e as Error).message}}
watch(selected,()=>{camera.value=undefined;rtsp.value='';cameraDirty.value=false;void refreshCamera(true)})
async function saveCamera(){
 if(mode.value==='rtsp'&&!rtsp.value.trim()){ElMessage.warning('请输入完整 RTSP 视频流地址');return}
 const id=selected.value;busy.value='camera'
 try{const saved=await call<CameraConfig>('PUT',`/furnaces/${id}/camera-config`,{mode:mode.value,...(mode.value==='rtsp'?{rtspUrl:rtsp.value.trim()}:{})});if(selected.value===id){camera.value=saved;rtsp.value=saved.rtspUrl;mode.value=saved.mode;cameraDirty.value=false}ElMessage.success('配置已保存，请等待视频连接状态更新')}catch(e){ElMessage.error((e as Error).message)}finally{busy.value=''}
}
onMounted(async()=>{if(currentUser.value?.role==='admin'){try{furnaces.value=await get<Furnace[]>('/furnaces');selected.value=furnaces.value[0]?.furnaceId??'';timer=setInterval(()=>void refreshCamera(),3000)}catch(e){cameraError.value=(e as Error).message}}})
onBeforeUnmount(()=>clearInterval(timer))
</script>
<template>
 <div class="section-title"><div><div class="eyebrow">SETTINGS</div><h1>设置</h1><p>管理自己的账户；管理员可以配置摄像头视频源。</p></div><span class="pill neutral">{{currentUser?.role==='admin'?'管理员':'普通用户 · 生产数据只读'}}</span></div>
 <div class="account-grid">
  <section class="panel"><div class="panel-heading"><h2>账户资料</h2></div><el-form class="form-body" label-position="top" @submit.prevent="profile"><el-form-item label="登录用户名"><el-input v-model="username" aria-label="登录用户名" maxlength="32" autocomplete="username"/></el-form-item><p class="small muted">3–32 位字母、数字或下划线；修改后用新用户名登录，历史与 Telegram 绑定保留。</p><el-form-item label="显示名称"><el-input v-model="displayName" aria-label="显示名称" maxlength="50"/></el-form-item><el-form-item label="当前密码（确认身份）"><el-input v-model="profilePassword" aria-label="资料修改当前密码" type="password" autocomplete="current-password"/></el-form-item><el-button native-type="submit" type="primary" :loading="busy==='profile'">保存账户资料</el-button></el-form></section>
  <section class="panel"><div class="panel-heading"><h2>修改密码</h2></div><el-form class="form-body" label-position="top" @submit.prevent="password"><el-form-item label="当前密码"><el-input v-model="oldPassword" aria-label="修改密码当前密码" type="password" autocomplete="current-password"/></el-form-item><el-form-item label="新密码"><el-input v-model="newPassword" aria-label="新密码" type="password" autocomplete="new-password"/></el-form-item><el-form-item label="确认新密码"><el-input v-model="confirmPassword" aria-label="确认新密码" type="password" autocomplete="new-password"/></el-form-item><p class="small muted">至少 8 字符，最多 72 字节。保存后所有设备退出登录。</p><el-button native-type="submit" type="primary" :loading="busy==='password'">修改密码并重新登录</el-button></el-form></section>
 </div>
 <section v-if="currentUser?.role==='admin'" class="panel camera-settings"><div class="panel-heading"><h2>摄像头 / RTSP 视频源</h2><el-select v-model="selected" :disabled="busy==='camera'" aria-label="配置摄像头所属炉子" style="width:190px"><el-option v-for="f in furnaces" :key="f.furnaceId" :value="f.furnaceId" :label="f.name"/></el-select></div><div class="form-body"><el-alert v-if="cameraError" :title="cameraError" type="error" :closable="false"/><template v-if="camera"><div class="camera-status"><span :class="['pill',camera.applied?'good':'warn']">{{camera.applied?'配置已应用':'等待应用'}}</span><span :class="['pill',camera.online?'good':'warn']">{{camera.online?'视频在线':'视频未连接'}}</span><span v-if="cameraDirty" class="pill warn">有未保存的修改</span><span class="muted">当前来源：{{camera.sourceHost||'尚未配置'}}</span></div><p class="small muted">{{camera.message}}</p><el-form label-position="top" @submit.prevent="saveCamera"><el-form-item label="视频来源"><el-radio-group v-model="mode" aria-label="视频来源" @change="cameraDirty=true"><el-radio value="simulated">模拟摄像头</el-radio><el-radio value="rtsp">RTSP / IP 摄像头</el-radio></el-radio-group></el-form-item><el-form-item v-if="mode==='rtsp'" label="RTSP 视频流地址"><el-input v-model="rtsp" aria-label="RTSP 视频流地址" type="text" autocomplete="off" @input="cameraDirty=true" placeholder="rtsp://用户名:密码@摄像头IP:554/视频路径" maxlength="2048"/></el-form-item><p class="small muted">支持 rtsp:// 和 rtsps://，使用 TCP。已保存地址会回显，仅管理员可查看和修改。摄像头需能从本机集群访问，建议使用 H.264 码流。</p><p class="small muted">有活动入炉周期时禁止切换。应用配置后会重新连接视频，短暂离线可能产生通知；配置已应用不代表摄像头已连通。</p><el-button native-type="submit" type="primary" :loading="busy==='camera'">保存视频源</el-button><el-button @click="refreshCamera()">刷新状态</el-button></el-form></template></div></section>
 <section v-else class="panel permission-note"><h2>当前权限</h2><p>你可以查看现场、历史与报警，管理自己的账户和 Telegram 通知。摄像头配置、FUXA、补录、复位和用户管理由管理员操作。</p></section>
</template>
<style scoped>
.account-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.panel h2{font-size:16px}.form-body{padding:22px}.form-body p{margin:0 0 18px;line-height:1.7}.camera-settings,.permission-note{margin-top:22px}.camera-status{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin-bottom:12px}.camera-settings .el-form{margin-top:24px}.permission-note{padding:24px}.permission-note p{line-height:1.8;color:var(--muted);margin-top:12px}@media(max-width:800px){.account-grid{grid-template-columns:1fr}}
</style>
